### ISSUE TITLE
Yolov5s performances problem?

### ISSUE THREAD

**Issue by luvwinnie** [DanaHan/Yolov5-in-Deepstream-5.0#2]
It seems like the performances on example video very bad, any idea on which issues?
The bounding boxes looks like not very stable.

**Comment by luvwinnie** [comment]
your code which seems like using the NvDsInferYoloCudaEngineGet for parsing the tensorrt engine, is this correct??

**Comment by DanaHan** [comment]
I have no problem. I can run yolov5 in deep stream 5.0 with fp16 model in a Xavier about 60 fps. Of course, the detect class num also influence the performance.

**Comment by luvwinnie** [comment]
@DanaHan I'm Glad to hear that! Maybe my model have some problem I would like to try again with your steps. Just in case, how did you run the app? Is it using the deepstream-app -c config_file?

**Comment by DanaHan** [comment]
LD_PRELOAD=$PWD/libmyplugin && deepstream-app -c config_file

**Comment by DanaHan** [comment]
> your code which seems like using the NvDsInferYoloCudaEngineGet for parsing the tensorrt engine, is this correct??

I am read all source codes recently. It seems that NvDsInferYoloCudaEngineGet is called only when you use non-tensorrt engine model (ONNX,UFFT, etc). And this function seems used to build engine model. I'm not sure whether this is correct.

**Comment by luvwinnie** [comment]
@DanaHan I tried again with your apps it seems like even "Person" class not predicted very well, your test seems like perform very well on Person?

**Comment by luvwinnie** [comment]
@DanaHan I delete all files and followed again your step, it works well! 
Seems like the weight of the yolov5s.pt not really good, I redownload all the weights and tensorrtx, and your repository. it work fine !
