### ISSUE TITLE
run LD_PRELOAD=./libnvdsinfer_custom_impl_Yolo.so deepstream-app -c deepstream_app_config_yoloV5.txt error

### ISSUE THREAD

**Issue by mhm0902** [DanaHan/Yolov5-in-Deepstream-5.0#8]
error:
ERROR: ../nvdsinfer/nvdsinfer_func_utils.cpp:33 [TRT]: INVALID_ARGUMENT: getPluginCreator could not find plugin YoloLayer_TRT version 1
ERROR: ../nvdsinfer/nvdsinfer_func_utils.cpp:33 [TRT]: safeDeserializationUtils.cpp (293) - Serialization Error in load: 0 (Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
ERROR: ../nvdsinfer/nvdsinfer_func_utils.cpp:33 [TRT]: INVALID_STATE: std::exception
ERROR: ../nvdsinfer/nvdsinfer_func_utils.cpp:33 [TRT]: INVALID_CONFIG: Deserialize the cuda engine failed.
ERROR: ../nvdsinfer/nvdsinfer_model_builder.cpp:1567 Deserialize engine failed from file: /opt/nvidia/deepstream/deepstream-5.0/sources/apps/sample_apps/deepstream-app/yolov5s.engine

**Comment by mhm0902** [comment]
Hi,我按照步骤操作，运行deepstream demo出现错误，请问是什么问题。

**Comment by Nicoladao** [comment]
请问您是怎么觉得这个问题的呢？我也碰到同样的问题
